name: laminas_dev

type: php:8.1

size: S

disk: 256

build:
  flavor: none

dependencies:
  php:
    composer/composer: "^2"

mounts:
  'data/cache':
    source: local
    source_path: data/cache

hooks:
  build: |
    set -e
    echo "#!/bin/bash\nset -e\n" > install_swoole.sh
    curl -s 'https://raw.githubusercontent.com/platformsh/snippets/main/src/install_swoole.sh' >> install_swoole.sh
    echo "Installing Swoole extension"
    bash install_swoole.sh swoole 4.6.2
    rm install_swoole.sh
    echo "Current PHP modules:"
    php -m
    echo "Installing platform.sh CLI"
    curl -sS https://platform.sh/cli/installer | php
    echo "- Setting up configuration"
    rm -f config/development.config.php config/autoload/*.local.php
    mv config/autoload/local.php.dist config/autoload/local.php
    echo "- Installing application dependencies"
    composer install --no-ansi --no-dev --no-interaction --no-scripts --no-plugins --optimize-autoloader
  deploy: |
    rm -rf data/cache/*

crons:
    snapshot:
        # Take a snapshot automatically every night at 3 am (UTC).
        spec: '0 3 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 8 am (UTC) on the 14th and 28th of every month.
        spec: '0 8 14,28 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi

web:
  commands:
    start: 'php vendor/bin/laminas mezzio:swoole:start'
  upstream:
    socket_family: tcp
    protocol: http
  locations:
    '/':
      passthru: true
