version: "3"
services:

  web:
    build:
      context: .
      dockerfile: .dev/Dockerfile
    env_file:
      - .env
    entrypoint: ['php', 'vendor/bin/laminas', 'mezzio:swoole:start']
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
