version: "3"
services:

  web:
    image: phpswoole/swoole:4.8-php8.1-alpine
    env_file:
      - .env
    entrypoint: ['php', 'vendor/bin/laminas', 'mezzio:swoole:start']
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
